version: '3'
services:
  # Servicio de base de datos PostgreSQL
  db_multitenant:
    image: postgres:13
    container_name: db_multitenant
    environment:
      POSTGRES_USER: cristian
      POSTGRES_PASSWORD: cristian
      POSTGRES_DB: multitenant_development
    ports:
      - "5434:5432"                 # Cambié el puerto para evitar conflictos
    volumes:
      - pgdata_multitenant:/var/lib/postgresql/data
    networks:
      - multitenant-network

  # Servicio de aplicación web Rails
  web_multitenant:
    build: .                        # Construye la imagen usando el Dockerfile actual
    container_name: web_multitenant
    command: bash -c "rm -f tmp/pids/server.pid && rails server -b '0.0.0.0'"
    volumes:
      - .:/usr/src/app
    ports:
      - "3002:3000"                 # Cambié el puerto para evitar conflictos
    depends_on:
      - db_multitenant
    environment:
      DATABASE_HOST: db_multitenant
      DATABASE_USERNAME: cristian
      DATABASE_PASSWORD: cristian
      DATABASE_NAME: multitenant_development
    networks:
      - multitenant-network

# Volumen para persistencia de datos
volumes:
  pgdata_multitenant:

# Red compartida para los servicios
networks:
  multitenant-network:
